<center><div class=rulebook-content-title>Guida agli allineamenti </div></center>
<div class=block>In Last Hope, come in ogni altro GDR, i personaggi si distinguono fra loro per il codice di comportamento che normalmente assumono in determinate situazioni e nella vita che conducono all'interno della città. <br>
In questo caso specifico, abbiamo deciso di assumere una distinzione fra gli atteggiamenti che è possibile comporre liberamente a seconda del personaggio che avete in mente. Questo non vuol dire naturalmente che se giocando il vostro personaggio capita in una serie di situazioni che lo porta a cambiare punto di vista, non abbiate paura a buttarvi in questa nuova strada. <br></div>

<center><div class=rulebook-content-title>Positivi </div></center>
<div class=block><b>Buono:</b> un personaggio buono pone il bene comune e la protezione dei più deboli e bisognosi al primo posto. Un personaggio buono è solito seguire le regole e l'autorità, anche se non ha alcuna difficoltà ad abbandonarle per perseguire degli scopi più alti meritevoli, ritrovandosi anche spesso ad infrangere la legge. <br>
<br><b>Legale Buono:</b> un personaggio legale buono crede che la via della legge sia la più adatta per un mondo migliore. La buona condotta e il rispetto dei codici sono la priorità, così come l'onore e la protezione degli esseri più deboli.<br> Quando le leggi si trasformano in mezzi per opprimere i deboli e favorire i più furbi, il legale buono si oppone strenuamente e si ribella contro tali barbarie. La ribellione di questo personaggio, tuttavia, consiste nell'azione all'interno del sistema che vuole cambiare, difficilmente si abbandona ad atteggiamenti da fuorilegge (seppur per una giusta causa) e questa è la più grande differenza che intercorre fra un <i>Legale</i> ed un <i>Buono</i> <br></div>

<center><div class=rulebook-content-title>Negativi </div></center>
<div class=block><b>Malvagio:</b> un personaggio di allineamento malvagio non impiega ogni occasione possibile per fare del male alla gente, ma è disposto a sfruttare debolezze e situazioni vantaggiose per trarne il massimo del profitto personale. Sostengono leggi e strutture fintanto che esse conferiscono a loro posizioni di potere e benefici, anche e soprattutto a costo della libertà e dei benefici altrui. 
<br><br><b>Caotico Malvagio:</b> un personaggio caotico malvagio è egocentrico, individualista ed egoista. Non ha alcun senso dell'onore, ed è pronto ad uccidere o danneggiare in qualsiasi modo chiunque si frapponga tra di lui e i suoi obiettivi o anche per puro e semplice divertimento. <br></div>

<center><div class=rulebook-content-title>Agnostici </div></center>
<div class=block><b>Neutrale:</b> un personaggio neutrale è un qualcuno che ha scelto di non schierarsi in nessuna delle fazioni che prevede un conflitto per un qualche ideale. Il personaggio non punta ad arrecare danni ad altri, così come non corre troppi rischi per aiutare il prossimo. La filosofia generale è quella di dare la priorità a sé stessi e/o delle persone che sono strettamente collegati a loro, e solamente in secondo piano di preoccuparsi dei problemi altrui. Può essere un personaggio dedito alle leggi degli uomini o della magia, oppure un criminale che tenta di non uccidere. I personaggi che appartengono a questa categoria non sono mai dei crudeli malviventi o dei benefattori magnanimi, ma hanno la possibilità di essere imbroglioni, opportunisti o degli occasionali gentiluomini o gentildonne.  </div>