<center><div class=titoli>Anticamente</div></center>
<div class=block>In principio l'universo era un luogo calmo in cui la magia fluiva liberamente generando creature nei pianeti che più erano adatti ad accogliere la vita. La Terra, il pianeta più prospero del sistema solare, è stata la culla della vita e della civiltà come la conosciamo oggi. Ma vi era un altro Regno che prosperava grazie all'influsso della Magia, ossia il <i>Regno Lunare</i>. <br>
Quando la popolazione iniziò a crescere, i Regnanti dei due pianeti decisero di unire la loro magia per espandere nell'intero sistema in una bolla protettiva che permettesse anche agli altri pianeti di fiorire e trasformarsi in luoghi ospitali per accogliere la vita che per secoli continuò a proliferare. Questo contribuì alla nascita di nuove popolazioni, che grate all'intervento benefico dei due pianeti regnanti, giurarono loro fedeltà costituendo così le fondamenta per quello che venne conosciuto come <i>”Silver Millennium”</i>.<br><br>

Per lunghi secoli regnò la pace e la serenità e l'epoca venne conosciuta come “Epoca d'Argento”, a causa dello splendore emanato dal Satellite della Terra che da ogni posizione era perfettamente visibile anche agli altri pianeti, come un faro di speranza e segnale di ricchezza e prosperità.<br>
In questo scenario, considerate le note minacce che circondavano il Sistema Solare, alcuni natii dei vari pianeti vennero addestrati alla Guerra: molti di loro divennero ufficiali sui Pianeti di origine e spesso presenziavano gli eventi sulla Luna, vero e proprio centro della vita del Regno, mentre altri partirono verso le fasce interne ed esterne degli Asteroidi, per costituire le difese più estreme ed essere sempre pronti a combattere, fungendo come vere e proprie “Sentinelle” a guardia della prosperità dei Pianeti.<br><br>

L'integrità di quello splendore, però, a poco a poco venne compromesso.</div>

<center><div class=titoli>Il Tradimento</div></center>
<div class="block">La genesi della corruzione del Silver Millenium ha inizio quando un'entità malvagia chiamata <i>il Fantasma</i>, proveniente dal Pianeta Eris, situato oltre Plutone, arriva al Palazzo della Luna. Abile attore, riesce in un primo momento a nascondere la sua natura oscura, avvicinandosi ad alcuni membri della famiglia reale: instaura un particolare rapporto di affinità con la Principessa Nehellenia, tingendo sempre più di nero la sua anima, portando ad emergere desideri di brama e di conquista che la Principessa vede riflesso in uno specchio di sua proprietà, maledetto dal Fantasma stesso, in grado di mostrarle realizzati tutti i suoi sogni di potere e di salita al trono. Nel momento in cui i reali intenti della creatura vengono scoperti egli viene esiliato su Eris, che viene tenuto sotto sorveglianza dalle Sentinelle della Fascia degli Asteroidi lì situata. Questo non impedisce tuttavia al Fantasma di agire, né ferma il seme del male ormai germogliato nell'anima della Principessa: attraverso lo specchio, l'essere spinge la Principessa a rubare il Cristallo d'Argento e le gemme planetarie custodite al Palazzo, in modo da poter essere l'unico sovrano del Regno Lunare. La Principessa, ormai corrotta, porta alla sua stessa corruzione altri nobili, tutti proveniente da Pianeti differenti, facendo leva sui loro desideri che vengono rappresentati dallo specchio da lei custodito e che si nutre delle loro ambizioni. Radunati i propri compagni, la Principessa mette in atto il suo tradimento: recatisi a Palazzo, cercano di impossessarsi del Cristallo d'Argento e delle gemme planetarie, senza farsi alcuno scrupolo nell'eliminare chi si pone tra loro ed il loro obiettivo. Scoperti, vengono rapidamente accerchiati e sconfitti, in attesa d'essere giudicati. Il processo li vede, ovviamente, colpevoli. La loro condanna: essere esiliati sul lato oscuro della Luna, marchiati attraverso la magia, per sempre, con il simbolo della mezza luna Nera rovesciata, simbolo di infamia e tradimento. <br>
Prima di essere esiliata la Principessa riesce a portare con sé lo specchio in cui ogni giorno, anche nel lato nero della Luna, si specchia, ripromettendo a se stessa e ai suoi seguaci che un giorno si sarebbero vendicati e avrebbero vinto. Isolati in un luogo freddo e sgradevole, con la loro unica reciproca compagnia, i seguaci e la Principessa divengono così uniti da essere al pari di una cosa sola. Il loro rancore, la loro rabbia, i loro desideri di conquista e di vendetta divengono talmente forti che lo specchio si tinge interamente di nero, tramutando quei sentimenti malevoli in un reale potere da poter essere usato a loro vantaggio. La Principessa, accortasi di ciò, inizia ad elaborare la loro fuga e la loro rivincita, elargendo i poteri forniti dallo specchio, fatti di inganni e di illusioni – così come loro sono stati resi ciechi dai propri desideri, ora possono rendere ciechi altri. Quattro tra i nobili seguaci mostrano di saper manovrare quei poteri in modo differente a seconda della loro indole e delle loro abilità e, nel tempo, iniziano ad indossare sulle loro vesti un simbolo con cui identificarsi a seconda della loro inclinazione, addestrando e aiutando gli altri esiliati nel manovrare la propria magia. </div>


<center><div class=titoli>La Profezia</div></center>
<div class=block> Un giorno, quando ancora il Regno era in pace e le minacce del “Fantasma”, tornato in esilio su Eris e della Principessa Nehellenia con i suoi seguaci erano state sventate e si pronosticava un lungo periodo di pace, gli Oracoli delle fasce di Asteroidi ebbero una profezia: <i>”Il Sole verrà oscurato, le tenebre mangeranno l'universo e il Millennio Nero prevarrà sull'Argento distruggendo ogni speranza”</i>. <br>
Questo fu l'inizio dei sospetti portati contro il Regno Lunare, che iniziò a logorare le Sentinelle che vegliavano sui satelliti, che iniziarono a meditare a riguardo la possibilità di iniziare ad intervenire loro direttamente, senza sapere di chi potersi fidare all'interno di quel regno che aveva dato loro i natali. </div>

<center><div class=titoli>L'inizio della Fine</div></center>
<div class=block>Tutto ha origine dalla Nebulosa Tau, situata in una regione del Braccio di Orione composta principalmente da grandi aggregati di nebulose oscure, ben evidenti in quanto oscurano la luce delle stelle della Via Lattea lì situate. <br>
Faraone 90 si è risvegliato. Egli ha in sé il potenziale magico oscuro della Nebulosa Tau, incontenibile quanto distruttore. Trascorrono 460 anni prima che possa arrivare al Regno Lunare: qui, dopo una sequela di distruzione lasciata alle spalle in altri punti della Galassia, il primo pianeta del Sistema Solare con cui Faraone 90 viene a contatto è Saturno. Complice il fatto che il pianeta nero sia in quel momento isolato dagli altri, Faraone 90 ne prende possesso in quanto è sprovvisto di una solida difesa. Abbatte coloro posti a proteggere il luogo del Silenzio e ne prende il comando: è da qui che il suo Esercito ha vita. Vengono riportate sul terreno di Saturno le anime di coloro che lì riposano, assoggettati al potere del Faraone e costretti a servirlo. La prima creatura riportata indietro è una donna che Faraone 90 ribattezza Despota 9 e a cui viene assegnata la missione di raggiungere gli altri Pianeti e annunciare l'arrivo della Distruzione.  <br><br>

Quando arrivò Faraone90, i Custodi furono i primi a soccombere alle sue bugie e al suo potere. Ingannati e convinti che esso li avrebbe aiutati a scovare il traditore, iniziarono ad aiutare l'Esercito del Silenzio a infiltrarsi nel Sistema Solare. Quando si accorsero dell'inganno ormai era troppo tardi: il potere di Faraone90 stava già dilagando anche in loro, risultando in principio indottrinati e in seguito posseduti dai Daimon. </div>

<center><div class=titoli>La Grande Guerra</div></center>
<div class=block>Quasi per tutta la durata del conflitto Le Sentinelle sono rimaste sotto il controllo dell'Esercito del Silenzio, combattendo per loro. Questo finché non arrivarono sulla superficie Lunare dove venne sferrato il primo vero e proprio attacco al cuore del Regno. <br>
I Guardiani non si resero conto immediatamente del tranello e combatterono al fianco dei Dominatori contro le Sentinelle corrotte, accorsi in difesa dalla Terra con la Discendenza reale del loro pianeta. <br>
Gli spiriti alleati e guardiani del pianeta Terra, vennero poi rispediti indietro assieme al Cristallo Dorato, assegnato loro dalla Regina Serenity per poterlo proteggere e garantire alla Terra l'ultimo baluardo di speranza per il loro Regno: erigere una barriera tramite il potere della Reliquia nel momento in cui la Luna sarebbe stata invasa dalle forze di Faraone90.<br>
Mentre la battaglia fra Sentinelle e Guardiani imperversava, un distaccamento delle forze guidate da Despota9 che si recò nel lato oscuro della Luna presentandosi a loro promettendo libertà, la Principessa china il capo con un sorriso, offrendo una fasulla e conveniente alleanza con il solo scopo di liberarsi dalle catene dell'esilio. <br>
Durante lo scontro sanguinoso, i Guardiani si accorsero della veridicità delle notizie arrivate dai pochi sopravvissuti degli Asteroidi, che annunciavano la corruzione forzata, l'inganno e la distruzione portata da Faraone90: questo portò i combattenti a tentare il tutto e per tutto per poter liberare le Sentinelle dall'influsso negativo del male, per liberarli e farli tornare in sé. <br>
Feriti e debilitati, vennero quindi mandati anch'essi sulla terra, per potersi riprendere e combattere al fianco dei Dominatori nel caso in cui la battaglia volgesse verso un epiteto disastroso.<br>
Purtroppo viste le tragiche circostanze, nessuno aveva avvertito i Dominatori della liberazione delle Sentinelle, quindi una volta che questi ultimi arrivarono sulla Terra, vennero maledetti e costretti a una forma animale. <br>
Un inghippo che venne in seguito chiarito, ma che non venne mai del tutto risolto dato che la maledizione fu sciolta soltanto in parte a causa della non completa appartenenza del Cristallo Dorato agli Spiriti, lasciando alle Sentinelle il legame con la loro forma animale e la costrizione a trasformarsi in essi tre volte al mese.  <br><br>

Contemporaneamente, sulla Luna la battaglia sanguinosa fra L'Esercito del Silenzio e gli Esiliati della Luna Nera, contro i Guardiani, divenne sempre più cruenta. Fu a quel punto che gli Esiliati preferirono la loro sopravvivenza: fuggirono sulla Terra portando con sé i cristalli planetari sottratti al Regno Lunare  ormai in rovina. Lì attesero il crollo definitivo del Silver Millennium. Quando i Custodi, resi conto della fuga della Luna Nera, li raggiunsero, dovettero subire la vendetta dell'oscurità che albergava in ognuno di loro. Scagliarono una maledizione che avrebbe distrutto per sempre le Sentinelle se non fosse stato per l'intervento dei Dominatori. L'epilogo ridusse la Luna Nera a disperdersi sulla Terra privata dei preziosi Cristalli e i Custodi maledetti, ma sopravvissuti. Ognuno di quegli Esiliati però  conservò un frammento dello Specchio nero andato distrutto. Il frammento più grande venne chiamato Cristallo Nero, rimasto tra le mani della Principessa Nehellenia e dei suoi diretti discendenti.   
<br><br>
La Regina Serenity, prima della fine della disfatta e di esalare il suo ultimo respiro, utilizzò pienamente il potere del Cristallo d'Argento, sprigionando una forza talmente grande da avvolgere le anime dei suoi Guardiani inviandoli sulla Terra per potergli permettere di reincarnarsi nei corpi dei Terrestri e garantire una speranza al futuro, prima che la Barriera eretta dai Dominatori raggiungesse il suo culmine attorno al pianeta.<br><br>

Venuta a sapere che la Regina del Regno Lunare è riuscita a trasportare le anime del Regno sulla Terra, Despota 9 cerca di distruggere e conquistare anche il pianeta superstite senza riuscirvi totalmente a causa della magia protettiva innalzata attorno ad esso. Quando viene a contatto con la barriera infatti, perde gran parte dei suoi poteri e cade sulla Terra aggrappandosi alla prima forma vivente che trova: un essere umano. Si perdono apparentemente le sue tracce. Faraone 90 non si avvicina alla Terra visto il destino di Despota9 e si ritira di nuovo verso la Nebulosa Tau, nell'attesa che il suo Messia risorga e lasciando il Sistema Solare deserto ad eccezione della Terra. Tuttavia la presenza, seppur dormiente, di Despota9 sulla Terra genera un flusso maligno in continua crescita che si insinua tra gli esseri umani salvi e i reincarnati, serpeggiando negli animi e corrompendoli.   </div>
