<center><div class=titoli>Velo</div></center>
<div class=block>Dopo il distaccamento dal proprio corpo, l'anima subisce un passaggio obbligato in quello che comunemente viene definito “Velo” o “Strappo”. Questo è un mondo di transizione fra la dimensione definita dai viventi “Oltremondo” e quella materiale in cui si trova Tokyo 0. 
Il velo è il luogo del tormento, in cui le anime che non riescono ad abbandonare la vita restano aggrappate senza passare oltre. Per questa ragione chi vi è stato (o afferma di esserci stato), lo descrive come un luogo freddo, dove la propria voce si perde e se si è troppo concentrati con lo sguardo sulla vita passata, è impossibile notare il sentiero luminoso che conduce all'Oltremondo.
In questo luogo, le anime che vi risiedono sperano di poter tornare alla vita nel loro vecchio corpo, ma ogni giorno che si passa incagliati nel Velo, è un giorno di tormento che logora l'anima e rischia di portare l'anima del defunto alla perdizione, che rischia di corrompere per sempre la sua spiritualità e trasformarla in una creatura maligna o in un mostro in grado di operare uno strappo fisico ed arrivare sul piano materiale.
<i>N.B. Vedere il paragrafo su Morte e Resurgo per ulteriori spiegazioni</i>
</div>
<center><div class=titoli>Oltremondo</div></center>
<div class=block>L'oltremondo è un luogo di pace che si trova oltre la frattura con il mondo Materiale, raggiungibile attraverso il Velo. 
Esso è identico al mondo di origine della persona, in cui l'anima viene purificata nel passaggio fra il velo e l'oltremondo, liberandosi di tutti i propri tormenti per poter tornare allo stato originale di purezza e neutralità, in attesa di potersi ricongiungere al corpo di un altro essere vivente, per continuare il suo ciclo vitale sulla Terra. </div>

<center><div class=titoli>Come sono nati il Velo e l'Oltremondo?</div></center>
<div class=block>In origine gli esseri appartenenti alla magia si disgregavano e si ricongiungevano alla Corrente Vitale della Magia, dando ad essa nuova forza e permettendo così la creazione di nuovi esseri viventi che sostituivano coloro che arrivavano al termine della loro longeva vita.
Non esisteva al tempo precedente ed in concomitanza del Silver Millennium il concetto di “Resurrezione” o di “Fusione dei mondi”. Ogni dimensione era perfettamente a se stante e divisa ed i confini erano custoditi dai Guardiani del Tempo.
Ma con la Grande Guerra, l'ultima speranza e la profonda disperazione portarono la Regina Serenity e la Principessa Nehellenia a corrompere questa naturale divisione fra i mondi costituiti dalla Magia, provocando lo “Strappo” che le persone conoscono come “Velo” e modificando la struttura stessa dell'Anima in modo che non si disgregasse ma che si tenesse aggrappata ai ricordi della vita passata, in modo da poter tramandare la storia del Silver Millennium e continuare a combattere, ognuno per la propria causa ed il proprio obiettivo. </div>

<center><div class=titoli>Chi può raggiungere il Velo?</div></center>
<div class=block>Solamente i Dominatori sono in grado di raggiunger la dimensione del Velo e tornare illesi: questo perché in realtà non sono esseri reincarnati e per questo definibili “Immortali”, che si legano ad un unico essere umano che usano come “ancora” per il passaggio fra un mondo e l'altro.
Tuttavia non possono raggiungere l'Oltremondo, perché per loro significherebbe recidere totalmente il legame con il corpo ospite, costringendoli a scomparire per sempre. 
Tuttavia non bisogna pensare che i Dominatori abbiano la possibilità di raggiungere il velo in ogni situazione: questi possono perdersi se non supportati correttamente da una seconda Ancora, possono rischiare di corrompersi e quindi di trasformarsi a loro volta in Spiriti malvagi, pur tornando nel loro corpo di origine.
Serve infatti una grande forza di volontà per poter sopportare la corruzione e la malvagità accumulata nei secoli nel Velo.</div>