<center><div class=titoli>Tokyo: anno 2016</div></center>
<div class=block>Dal momento del risveglio dei vari combattenti delle Dinastie, la lotta per il potere e per la conquista dei punti nevralgici della Magia presenti a Tokyo a causa della caduta delle Reliquie in quei punti, ha imperversato senza tregua all'interno della città, scatenando talvolta dei cataclismi che hanno inciso non sempre positivamente sul pianeta e rendendo ugualmente sanguinose le battaglie dei contendenti al potere: chi per ristabilire l'ordine originario, chi per vendetta, chi per assicurarsi una nuova supremazia sulle altre Dinastie e chi per instaurare un nuovo ordine, nel bene o nel male. <br><br>

In questo scenario, la minaccia della magia della Regina Metaria, energia negativa del Sole, si abbatte sul mondo rendendo i membri delle varie Dinastie ugualmente inconsapevoli e minacciati, ma grazie alla loro presenza Tokyo è l'ultima città a resistere e moltissime persone da tutte le parti del pianeta accorrono per trovare riparo in essa, grazie a coloro che credettero nella leggenda tramandata da padre in figlio attraverso i millenni: la magia bianca della Luna riuscirà a proteggere l'umanità. <br>
Durante una battaglia per la sopravvivenza e per tentare di contenere al di fuori dei limiti di Tokyo il potere maligno di Metaria, il Cristallo d'Argento sembra attivarsi inspiegabilmente da solo e provoca una stasi di tutte le forme di vita radunate a Tokyo (circa 13 milioni, tra cui moltissime etnie diverse provenienti dalle varie parti del pianeta) di fatto cristallizzandole, con lo scopo di proteggerle e preservarle oltre che attingere alla loro magia per potersi mantenere attivo. La città viene debilitata e ridotta quasi in macerie a causa di quell'esplosione di potere, ma l'avanzata della Regina Metaria viene bloccata dalla barriera così generata e rendendole impossibile da oltrepassare, costringendola alla ritirata non riuscendo a trovare alcuna fonte di sostentamento e di vita a cui attingere. <br>
Cala il silenzio sul mondo: Tokyo è l'unica città sopravvissuta.</div>

<center><div class=titoli>Tokyo: anno 0</div></center>
<div class=block>Dopo un tempo che nessuno sa quantificare, la cristallizzazione inizia a frantumarsi lentamente. Le persone iniziano a poco a poco a risvegliarsi a frazioni, ricominciando a vivere nella città distrutta e restituendole nuova vita. Un periodo di ricostruzione segue a questo momento e giacché il mondo è stato stravolto, tutto ricomincia: anche il tempo. E' l'anno 0, l'anno dell'inizio. La ripresa è lenta, graduale, ma efficiente. </div>

<center><div class=titoli>Tokyo, anno 316. Oggi. </div></center>
<div class=block>
<u>numero abitanti:</u> <i>10 milioni </i>
Sono trascorsi tre secoli e sedici anni dall'anno 0. 
Una città piena di vita, popolata dai discendenti di coloro che sono sopravvissuti. Strutturata su 10 Distretti con a capo ciascuno un sindaco che permette che tutto funzioni al meglio. Un precario equilibrio di tecnologia e sfruttamento delle risorse presenti, dovendosi poi affidare ad uno sviluppo spesso duro e difficoltoso. L'epoca del legno ha ceduto il passo al metallo. Il grande Palazzo di Cristallo situato a Shinagawa è il simbolo della città, rappresentante lo scoppio di potere che ha protetto l'attuale vita; è anche il luogo che, si vocifera, contenga ancora le persone non svegliate. Esse sono destinate a rimanere nel loro sonno o a riprendere coscienza di sé senza che qualcuno sappia quando. Il Palazzo è intoccabile e rispettato, vissuto come un luogo magico e sacro. <br>
I primi risvegliati hanno preso in mano le redini della città, ricreato una società, ricreato un piccolo mondo concentrato su una superficie limitata che attorno non ha, apparentemente, nulla. Non è strano dunque che di tanto in tanto nuovi addormentati escano dal loro torpore di cristallo e riprendano a vivere per le strade di una Tokyo in continuo fermento.  </div>